add_library(optimisation ${SRC_MODEL})
add_library(Antares::optimisation ALIAS optimisation)
target_sources(optimisation
        PRIVATE
        HebdoProblemToLpsTranslator.cpp
        LegacyFiller.cpp
        LinearProblemMatrix.cpp
        LinearProblemMatrixStartUpCosts.cpp
        ProblemMatrixEssential.cpp
        QuadraticProblemMatrix.cpp
        adequacy_patch_csr/adq_patch_curtailment_sharing.cpp
        adequacy_patch_csr/adq_patch_post_process_list.cpp
        adequacy_patch_csr/constraints/CsrAreaBalance.cpp
        adequacy_patch_csr/constraints/CsrBindingConstraintHour.cpp
        adequacy_patch_csr/constraints/CsrFlowDissociation.cpp
        adequacy_patch_csr/construct_problem_constraints_RHS.cpp
        adequacy_patch_csr/construct_problem_variables.cpp
        adequacy_patch_csr/count_constraints_variables.cpp
        adequacy_patch_csr/csr_quadratic_problem.cpp
        adequacy_patch_csr/set_problem_cost_function.cpp
        adequacy_patch_csr/set_variable_boundaries.cpp
        adequacy_patch_csr/solve_problem.cpp
        constraints/AbstractStartUpCostsGroup.cpp
        constraints/AreaBalance.cpp
        constraints/AreaHydroLevel.cpp
        constraints/AreaHydroLevelGroup.cpp
        constraints/BindingConstraintDay.cpp
        constraints/BindingConstraintDayGroup.cpp
        constraints/BindingConstraintHour.cpp
        constraints/BindingConstraintWeek.cpp
        constraints/BindingConstraintWeekGroup.cpp
        constraints/ConsistenceNumberOfDispatchableUnits.cpp
        constraints/ConsistenceNumberOfDispatchableUnitsGroup.cpp
        constraints/ConstraintBuilder.cpp
        constraints/ExchangeBalance.cpp
        constraints/ExchangeBalanceGroup.cpp
        constraints/FictitiousLoad.cpp
        constraints/FinalStockEquivalent.cpp
        constraints/FinalStockExpression.cpp
        constraints/FinalStockGroup.cpp
        constraints/FlowDissociation.cpp
        constraints/Group1.cpp
        constraints/HydraulicSmoothingGroup.cpp
        constraints/HydroPower.cpp
        constraints/HydroPowerGroup.cpp
        constraints/HydroPowerSmoothingUsingVariationMaxDown.cpp
        constraints/HydroPowerSmoothingUsingVariationMaxUp.cpp
        constraints/HydroPowerSmoothingUsingVariationSum.cpp
        constraints/MaxHydroPower.cpp
        constraints/MaxPumping.cpp
        constraints/MaxPumpingGroup.cpp
        constraints/MinDownTime.cpp
        constraints/MinDownTimeGroup.cpp
        constraints/MinHydroPower.cpp
        constraints/MinMaxHydroPowerGroup.cpp
        constraints/NbDispUnitsMinBoundSinceMinUpTime.cpp
        constraints/NbDispUnitsMinBoundSinceMinUpTimeGroup.cpp
        constraints/NbUnitsOutageLessThanNbUnitsStop.cpp
        constraints/NbUnitsOutageLessThanNbUnitsStopGroup.cpp
        constraints/PMaxDispatchableGeneration.cpp
        constraints/PMinDispatchableGeneration.cpp
        constraints/PMinMaxDispatchableGenerationGroup.cpp
        constraints/ShortTermStorageCostVariation.cpp
        constraints/ShortTermStorageCostVariationInjectionBackward.cpp
        constraints/ShortTermStorageCostVariationInjectionForward.cpp
        constraints/ShortTermStorageCostVariationWithdrawalBackward.cpp
        constraints/ShortTermStorageCostVariationWithdrawalForward.cpp
        constraints/ShortTermStorageCumulation.cpp
        constraints/ShortTermStorageLevel.cpp
        constraints/constraint_builder_utils.cpp
        base_post_process.cpp
        include/antares/solver/optimisation/HebdoProblemToLpsTranslator.h
        include/antares/solver/optimisation/base_post_process.h
        include/antares/solver/optimisation/LegacyFiller.h
        include/antares/solver/optimisation/LegacyOrtoolsLinearProblem.h
        include/antares/solver/optimisation/LinearProblemMatrix.h
        include/antares/solver/optimisation/LinearProblemMatrixStartUpCosts.h
        include/antares/solver/optimisation/ProblemMatrixEssential.h
        include/antares/solver/optimisation/QuadraticProblemMatrix.h
        include/antares/solver/optimisation/adequacy_patch_csr/adq_patch_curtailment_sharing.h
        include/antares/solver/optimisation/adequacy_patch_csr/adq_patch_post_process_list.h
        include/antares/solver/optimisation/adequacy_patch_csr/constraints/CsrAreaBalance.h
        include/antares/solver/optimisation/adequacy_patch_csr/constraints/CsrBindingConstraintHour.h
        include/antares/solver/optimisation/adequacy_patch_csr/constraints/CsrFlowDissociation.h
        include/antares/solver/optimisation/adequacy_patch_csr/count_constraints_variables.h
        include/antares/solver/optimisation/adequacy_patch_csr/csr_quadratic_problem.h
        include/antares/solver/optimisation/adequacy_patch_csr/hourly_csr_problem.h
        include/antares/solver/optimisation/constraints/AbstractStartUpCostsGroup.h
        include/antares/solver/optimisation/constraints/AreaBalance.h
        include/antares/solver/optimisation/constraints/AreaHydroLevel.h
        include/antares/solver/optimisation/constraints/AreaHydroLevelGroup.h
        include/antares/solver/optimisation/constraints/BindingConstraintDay.h
        include/antares/solver/optimisation/constraints/BindingConstraintDayGroup.h
        include/antares/solver/optimisation/constraints/BindingConstraintHour.h
        include/antares/solver/optimisation/constraints/BindingConstraintWeek.h
        include/antares/solver/optimisation/constraints/BindingConstraintWeekGroup.h
        include/antares/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnits.h
        include/antares/solver/optimisation/constraints/ConsistenceNumberOfDispatchableUnitsGroup.h
        include/antares/solver/optimisation/constraints/ConstraintBuilder.h
        include/antares/solver/optimisation/constraints/ConstraintGroup.h
        include/antares/solver/optimisation/constraints/ExchangeBalance.h
        include/antares/solver/optimisation/constraints/ExchangeBalanceGroup.h
        include/antares/solver/optimisation/constraints/FictitiousLoad.h
        include/antares/solver/optimisation/constraints/FinalStockEquivalent.h
        include/antares/solver/optimisation/constraints/FinalStockExpression.h
        include/antares/solver/optimisation/constraints/FinalStockGroup.h
        include/antares/solver/optimisation/constraints/FlowDissociation.h
        include/antares/solver/optimisation/constraints/Group1.h
        include/antares/solver/optimisation/constraints/HydraulicSmoothingGroup.h
        include/antares/solver/optimisation/constraints/HydroPower.h
        include/antares/solver/optimisation/constraints/HydroPowerGroup.h
        include/antares/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxDown.h
        include/antares/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationMaxUp.h
        include/antares/solver/optimisation/constraints/HydroPowerSmoothingUsingVariationSum.h
        include/antares/solver/optimisation/constraints/MaxHydroPower.h
        include/antares/solver/optimisation/constraints/MaxPumping.h
        include/antares/solver/optimisation/constraints/MaxPumpingGroup.h
        include/antares/solver/optimisation/constraints/MinDownTime.h
        include/antares/solver/optimisation/constraints/MinDownTimeGroup.h
        include/antares/solver/optimisation/constraints/MinHydroPower.h
        include/antares/solver/optimisation/constraints/MinMaxHydroPowerGroup.h
        include/antares/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTime.h
        include/antares/solver/optimisation/constraints/NbDispUnitsMinBoundSinceMinUpTimeGroup.h
        include/antares/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStop.h
        include/antares/solver/optimisation/constraints/NbUnitsOutageLessThanNbUnitsStopGroup.h
        include/antares/solver/optimisation/constraints/PMaxDispatchableGeneration.h
        include/antares/solver/optimisation/constraints/PMinDispatchableGeneration.h
        include/antares/solver/optimisation/constraints/PMinMaxDispatchableGenerationGroup.h
        include/antares/solver/optimisation/constraints/ShortTermStorageCostVariation.h
        include/antares/solver/optimisation/constraints/ShortTermStorageCumulation.h
        include/antares/solver/optimisation/constraints/ShortTermStorageLevel.h
        include/antares/solver/optimisation/constraints/constraint_builder_utils.h
        include/antares/solver/optimisation/opt_appel_solveur_quadratique.h
        include/antares/solver/optimisation/opt_constants.h
        include/antares/solver/optimisation/opt_export_structure.h
        include/antares/solver/optimisation/opt_fonctions.h
        include/antares/solver/optimisation/opt_optimisation_hebdo.h
        include/antares/solver/optimisation/opt_rename_problem.h
        include/antares/solver/optimisation/optim_post_process_list.h
        include/antares/solver/optimisation/post_process_commands.h
        include/antares/solver/optimisation/weekly_optimization.h
        include/antares/solver/optimisation/ortools_simplexe.h
        include/antares/solver/optimisation/ortools_quadratic_wrapper.h
        opt_alloc_probleme_a_optimiser.cpp
        opt_appel_solveur_lineaire.cpp
        opt_appel_solveur_quadratique.cpp
        opt_calcul_des_pmin_MUT_MDT.cpp
        opt_chainage_intercos.cpp
        opt_construction_variables_couts_demarrages.cpp
        opt_construction_variables_optimisees_lineaire.cpp
        opt_construction_variables_optimisees_quadratique.cpp
        opt_decompte_variables_et_contraintes.cpp
        opt_decompte_variables_et_contraintes.cpp
        opt_decompte_variables_et_contraintes_couts_demarrage.cpp
        opt_export_structure.cpp
        opt_gestion_des_bornes_cas_lineaire.cpp
        opt_gestion_des_bornes_cas_quadratique.cpp
        opt_gestion_des_bornes_couts_demarrage.cpp
        opt_gestion_des_couts_cas_lineaire.cpp
        opt_gestion_des_couts_cas_quadratique.cpp
        opt_gestion_des_couts_cas_quadratique.cpp
        opt_gestion_des_couts_couts_demarrage.cpp
        opt_gestion_des_pmin.cpp
        opt_gestion_second_membre_cas_lineaire.cpp
        opt_gestion_second_membre_cas_quadratique.cpp
        opt_gestion_second_membre_couts_demarrage.cpp
        opt_gestion_second_membre_couts_demarrage.cpp
        opt_init_contraintes_hydrauliques.cpp
        opt_init_minmax_groupes_couts_demarrage.cpp
        opt_liberation_problemes_simplexe.cpp
        opt_nombre_min_groupes_demarres_couts_demarrage.cpp
        opt_numero_de_jour_du_pas_de_temps.cpp
        opt_optimisation_hebdo.cpp
        opt_optimisation_lineaire.cpp
        opt_pilotage_optimisation_lineaire.cpp
        opt_pilotage_optimisation_quadratique.cpp
        opt_rename_problem.cpp
        opt_restaurer_les_donnees.cpp
        opt_verification_presence_reserve_jmoins1.cpp
        optim_post_process_list.cpp
        ortools_simplexe.cpp
        ortools_quadratic_wrapper.cpp
        post_process_commands.cpp
        variables/VariableManagement.cpp
        variables/VariableManagement.h
        variables/VariableManagerUtils.cpp
        variables/VariableManagerUtils.h
        weekly_optimization.cpp
        ortools_wrapper.cpp
        include/antares/solver/optimisation/ortools_wrapper.h
        post_process_commands.cpp
        post_process_commands.cpp
        include/antares/solver/optimisation/post_process_commands.h
        include/antares/solver/optimisation/common-hydro-remix.h
        common-hydro-remix.cpp
        shave-peaks-by-remix-hydro.cpp
        include/antares/solver/optimisation/shave-peaks-by-remix-hydro.h
        include/antares/solver/optimisation/common-hydro-levels.h
        common-hydro-levels.cpp

)

target_link_libraries(optimisation
        PUBLIC
        sirius_solver
        Antares::benchmarking
        Antares::optimization-options
        Antares::lps
        PRIVATE
        Antares::solverUtils
        infeasible_problem_analysis
        Antares::linear-problem-api
        Antares::linear-problem-data-impl
        Antares::linear-problem-mpsolver-impl
        # modeler
        Antares::optim-model-filler
        Antares::antares-study-system-model
)

target_include_directories(optimisation
        PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
)

install(DIRECTORY include/antares
        DESTINATION "include"
)
