# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Antares::solver_api Antares::study Antares::study-loader Antares::file-tree-study-loader Antares::antares-solver-simulation Antares::yuni-static-core Antares::array Antares::date Antares::inifile Antares::stdcxx Antares::StudyUtils Antares::utils Antares::correlation Antares::path Antares::mersenne Antares::result_writer Antares::series Antares::antares-core Antares::antares-solver-hydro Antares::exception Antares::benchmarking Antares::antares-solver-variable Antares::lps Antares::application Antares::infoCollection Antares::concurrency Antares::misc Antares::model_antares Antares::antares-solver-ts-generator Antares::shave-peaks-by-remix-hydro Antares::io Antares::jit Antares::AntaresMemory Antares::logs Antares::locator Antares::antares-config-lib Antares::solver-lib Antares::sys Antares::signal-handling Antares::antares-solver-variable-info Antares::optimization-options Antares::resources Antares::infeasible_problem_analysis Antares::linear-problem-api Antares::linear-problem-data-impl Antares::linear-problem-mpsolver-impl Antares::args_helper Antares::checks Antares::locale Antares::yuni-static-uuid Antares::antares-solver)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target Antares::solver_api
add_library(Antares::solver_api STATIC IMPORTED)

set_target_properties(Antares::solver_api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::file-tree-study-loader>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::study-loader>;\$<LINK_ONLY:Antares::antares-solver-simulation>;Antares::optimization-options;Antares::lps"
)

# Create imported target Antares::study
add_library(Antares::study STATIC IMPORTED)

set_target_properties(Antares::study PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::date;Antares::inifile;Antares::stdcxx;Antares::StudyUtils;Antares::utils;Antares::correlation;Antares::path;Antares::mersenne;Antares::result_writer;Antares::series;Antares::array;Antares::antares-core;Antares::antares-solver-simulation;Antares::antares-solver-hydro;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::benchmarking>;\$<LINK_ONLY:Antares::antares-solver-variable>"
)

# Create imported target Antares::study-loader
add_library(Antares::study-loader INTERFACE IMPORTED)

set_target_properties(Antares::study-loader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::file-tree-study-loader
add_library(Antares::file-tree-study-loader STATIC IMPORTED)

set_target_properties(Antares::file-tree-study-loader PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study-loader;Antares::result_writer;Antares::study;Antares::application"
)

# Create imported target Antares::antares-solver-simulation
add_library(Antares::antares-solver-simulation STATIC IMPORTED)

set_target_properties(Antares::antares-solver-simulation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::infoCollection;Antares::yuni-static-core;Antares::study;Antares::result_writer;Antares::concurrency;Antares::utils;Antares::misc;Antares::model_antares;Antares::antares-solver-hydro;Antares::antares-solver-variable;Antares::antares-solver-ts-generator;Antares::shave-peaks-by-remix-hydro"
)

# Create imported target Antares::yuni-static-core
add_library(Antares::yuni-static-core STATIC IMPORTED)

set_target_properties(Antares::yuni-static-core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-pthread"
)

# Create imported target Antares::array
add_library(Antares::array STATIC IMPORTED)

set_target_properties(Antares::array PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::io;Antares::jit;Antares::AntaresMemory;Antares::StudyUtils"
)

# Create imported target Antares::date
add_library(Antares::date STATIC IMPORTED)

set_target_properties(Antares::date PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::inifile
add_library(Antares::inifile STATIC IMPORTED)

set_target_properties(Antares::inifile PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Boost::headers>"
)

# Create imported target Antares::stdcxx
add_library(Antares::stdcxx STATIC IMPORTED)

set_target_properties(Antares::stdcxx PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::StudyUtils
add_library(Antares::StudyUtils STATIC IMPORTED)

set_target_properties(Antares::StudyUtils PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::utils
add_library(Antares::utils STATIC IMPORTED)

set_target_properties(Antares::utils PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-unused-variable"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ortools::ortools;sirius_solver;Antares::study;Antares::result_writer;Antares::optimization-options;Antares::antares-core"
)

# Create imported target Antares::correlation
add_library(Antares::correlation STATIC IMPORTED)

set_target_properties(Antares::correlation PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::array>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::locator>"
)

# Create imported target Antares::path
add_library(Antares::path STATIC IMPORTED)

set_target_properties(Antares::path PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::mersenne
add_library(Antares::mersenne STATIC IMPORTED)

set_target_properties(Antares::mersenne PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::result_writer
add_library(Antares::result_writer STATIC IMPORTED)

set_target_properties(Antares::result_writer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::benchmarking;Antares::yuni-static-core;\$<LINK_ONLY:MINIZIP::minizip-ng>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::io>;\$<LINK_ONLY:Antares::concurrency>"
)

# Create imported target Antares::series
add_library(Antares::series STATIC IMPORTED)

set_target_properties(Antares::series PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::array;Antares::antares-core"
)

# Create imported target Antares::antares-core
add_library(Antares::antares-core STATIC IMPORTED)

set_target_properties(Antares::antares-core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::logs;Antares::exception;Antares::study;Antares::antares-config-lib"
)

# Create imported target Antares::antares-solver-hydro
add_library(Antares::antares-solver-hydro STATIC IMPORTED)

set_target_properties(Antares::antares-solver-hydro PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::model_antares>;\$<LINK_ONLY:Antares::antares-solver-variable>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::mersenne>;sirius_solver;Antares::date;Antares::result_writer"
)

# Create imported target Antares::exception
add_library(Antares::exception STATIC IMPORTED)

set_target_properties(Antares::exception PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study;\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::benchmarking
add_library(Antares::benchmarking STATIC IMPORTED)

set_target_properties(Antares::benchmarking PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::inifile>"
)

# Create imported target Antares::antares-solver-variable
add_library(Antares::antares-solver-variable STATIC IMPORTED)

set_target_properties(Antares::antares-solver-variable PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::antares-solver-simulation;\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::study>"
)

# Create imported target Antares::lps
add_library(Antares::lps STATIC IMPORTED)

set_target_properties(Antares::lps PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::application
add_library(Antares::application STATIC IMPORTED)

set_target_properties(Antares::application PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::study;Antares::infoCollection;Antares::solver-lib;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::sys>;\$<LINK_ONLY:Antares::utils>;\$<LINK_ONLY:Antares::signal-handling>;\$<LINK_ONLY:Antares::resources>;\$<LINK_ONLY:Antares::file-tree-study-loader>"
)

# Create imported target Antares::infoCollection
add_library(Antares::infoCollection STATIC IMPORTED)

set_target_properties(Antares::infoCollection PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::benchmarking;Antares::study"
)

# Create imported target Antares::concurrency
add_library(Antares::concurrency STATIC IMPORTED)

set_target_properties(Antares::concurrency PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core"
)

# Create imported target Antares::misc
add_library(Antares::misc STATIC IMPORTED)

set_target_properties(Antares::misc PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::StudyUtils>;Antares::yuni-static-core;Antares::study"
)

# Create imported target Antares::model_antares
add_library(Antares::model_antares STATIC IMPORTED)

set_target_properties(Antares::model_antares PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-unused-variable"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::utils;sirius_solver;Antares::antares-solver-simulation;Antares::benchmarking;Antares::optimization-options;Antares::lps;\$<LINK_ONLY:Antares::infeasible_problem_analysis>;\$<LINK_ONLY:Antares::linear-problem-api>;\$<LINK_ONLY:Antares::linear-problem-data-impl>;\$<LINK_ONLY:Antares::linear-problem-mpsolver-impl>"
)

# Create imported target Antares::antares-solver-ts-generator
add_library(Antares::antares-solver-ts-generator STATIC IMPORTED)

set_target_properties(Antares::antares-solver-ts-generator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::result_writer>;\$<LINK_ONLY:Antares::array>;\$<LINK_ONLY:Antares::benchmarking>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::misc>;\$<LINK_ONLY:Antares::antares-solver-simulation>"
)

# Create imported target Antares::shave-peaks-by-remix-hydro
add_library(Antares::shave-peaks-by-remix-hydro STATIC IMPORTED)

set_target_properties(Antares::shave-peaks-by-remix-hydro PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::io
add_library(Antares::io STATIC IMPORTED)

set_target_properties(Antares::io PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::jit
add_library(Antares::jit STATIC IMPORTED)

set_target_properties(Antares::jit PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;Antares::logs"
)

# Create imported target Antares::AntaresMemory
add_library(Antares::AntaresMemory STATIC IMPORTED)

set_target_properties(Antares::AntaresMemory PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;Antares::logs;\$<LINK_ONLY:Antares::sys>"
)

# Create imported target Antares::logs
add_library(Antares::logs STATIC IMPORTED)

set_target_properties(Antares::logs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core"
)

# Create imported target Antares::locator
add_library(Antares::locator STATIC IMPORTED)

set_target_properties(Antares::locator PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::study;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::resources>"
)

# Create imported target Antares::antares-config-lib
add_library(Antares::antares-config-lib STATIC IMPORTED)

set_target_properties(Antares::antares-config-lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::solver-lib
add_library(Antares::solver-lib INTERFACE IMPORTED)

set_target_properties(Antares::solver-lib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::args_helper;Antares::date;Antares::benchmarking;Antares::result_writer;Antares::sys;Antares::infoCollection;Antares::checks;Antares::misc;Antares::optimization-options;Antares::signal-handling;Antares::locale;Antares::yuni-static-uuid;Antares::yuni-static-core;Antares::antares-solver-hydro;Antares::antares-solver-variable;Antares::antares-solver-simulation;Antares::antares-solver-ts-generator;Antares::model_antares;Antares::antares-core"
)

# Create imported target Antares::sys
add_library(Antares::sys STATIC IMPORTED)

set_target_properties(Antares::sys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::inifile>;\$<LINK_ONLY:Antares::antares-config-lib>"
)

# Create imported target Antares::signal-handling
add_library(Antares::signal-handling STATIC IMPORTED)

set_target_properties(Antares::signal-handling PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::study>;Antares::result_writer;Antares::AntaresMemory"
)

# Create imported target Antares::antares-solver-variable-info
add_library(Antares::antares-solver-variable-info STATIC IMPORTED)

set_target_properties(Antares::antares-solver-variable-info PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::antares-core>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::antares-solver-simulation>"
)

# Create imported target Antares::optimization-options
add_library(Antares::optimization-options INTERFACE IMPORTED)

set_target_properties(Antares::optimization-options PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::resources
add_library(Antares::resources STATIC IMPORTED)

set_target_properties(Antares::resources PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::yuni-static-core;\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::antares-config-lib>"
)

# Create imported target Antares::infeasible_problem_analysis
add_library(Antares::infeasible_problem_analysis STATIC IMPORTED)

set_target_properties(Antares::infeasible_problem_analysis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ortools::ortools>;\$<LINK_ONLY:Boost::headers>;\$<LINK_ONLY:Antares::logs>"
)

# Create imported target Antares::linear-problem-api
add_library(Antares::linear-problem-api STATIC IMPORTED)

set_target_properties(Antares::linear-problem-api PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target Antares::linear-problem-data-impl
add_library(Antares::linear-problem-data-impl STATIC IMPORTED)

set_target_properties(Antares::linear-problem-data-impl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-api"
)

# Create imported target Antares::linear-problem-mpsolver-impl
add_library(Antares::linear-problem-mpsolver-impl STATIC IMPORTED)

set_target_properties(Antares::linear-problem-mpsolver-impl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "Antares::linear-problem-api;Antares::logs;Antares::utils;ortools::ortools"
)

# Create imported target Antares::args_helper
add_library(Antares::args_helper STATIC IMPORTED)

set_target_properties(Antares::args_helper PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::checks
add_library(Antares::checks STATIC IMPORTED)

set_target_properties(Antares::checks PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::logs>;\$<LINK_ONLY:Antares::yuni-static-core>;\$<LINK_ONLY:Antares::exception>;\$<LINK_ONLY:Antares::study>;\$<LINK_ONLY:Antares::antares-core>"
)

# Create imported target Antares::locale
add_library(Antares::locale STATIC IMPORTED)

set_target_properties(Antares::locale PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Antares::yuni-static-core>"
)

# Create imported target Antares::yuni-static-uuid
add_library(Antares::yuni-static-uuid STATIC IMPORTED)

set_target_properties(Antares::yuni-static-uuid PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-pthread;uuid"
)

# Create imported target Antares::antares-solver
add_executable(Antares::antares-solver IMPORTED)

set_target_properties(Antares::antares-solver PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

if(CMAKE_VERSION VERSION_LESS 3.1.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.1.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/AntaresTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
